[build]
  command   = "npm --prefix frontend ci && npm --prefix frontend run build"
  publish   = "frontend/dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"


# API → Functions (optional if you call /.netlify/functions/ask directly)
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

# SPA fallback so / routes don’t 404
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
